spring:
  application:
    name: cinema-api
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cinema?serverTimezone=America/Bogota&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 
cinema:
  swagger:
    controller: com.cinema.infrastructure.rest
  audit:
    database: cinema
    table:
      audit: audit
      movie: movie
      serie: serie
      gender: gender
      server: server
      serverMovie: "server movie"  
tmdb:
  base:
    url: https://api.themoviedb.org/3/
    language: "language=es"
    image:
      original: https://image.tmdb.org/t/p/original
      svg: https://image.tmdb.org/t/p/original
      jpg: https://image.tmdb.org/t/p/w500
    key: 073e12be03eeaf53ed1368a2b178493c
  find:
    movie:
      url: "{baseUrl}search/movie?api_key={tmdbBaseKey}&{language}&query={query}"
      id:
        url: "{baseUrl}movie/{id}?api_key={tmdbBaseKey}&{language}"
      image:
        url: "{baseUrl}movie/{id}/images?api_key={tmdbBaseKey}&{language}"
    serie:
      url: "{baseUrl}search/tv?api_key={tmdbBaseKey}&{language}&query={query}"
      id:
        url: "{baseUrl}tv/{id}?api_key={tmdbBaseKey}&{language}"
      seanson: 
        url: "{baseUrl}tv/{id}/season/{number}?api_key={tmdbBaseKey}&{language}"
      changes:
        url: "{baseUrl}tv/{id}/changes?api_key={tmdbBaseKey}&{language}"
      image: 
        url: "{baseUrl}tv/{id}/season/{number}/images?api_key={tmdbBaseKey}&{language}"
      video:
        url: "{baseUrl}tv/{id}/season/{number}/videos?api_key={tmdbBaseKey}&{language}"
    genre:
      url: "{baseUrl}genre/movie/list?api_key={tmdbBaseKey}&{language}" 